### ISSUE TITLE
Index Error in generate.py

### ISSUE THREAD

**Issue by G0LDF0X** [DegardinBruno/Kinetic-GAN#11]
Hello,

I'm trying to run python.py today and I faced the following error message.

Traceback (most recent call last):
  File "generate.py", line 24, in <module>
    out         = general.check_runs('kinetic-gan', id=-1)
  File "/root/Kinetic-GAN/utils/general.py", line 17, in check_runs
    out  = os.path.join(exps_path,'exp'+str(len(exps)+1)) if not id else os.path.join(exps_path, exps[id])
IndexError: list index out of range

But in my directory, there's no folder name 'exp0' or other things in runs/kinetic-gan folder.

Could you tell me how to solve this error problem?

**Comment by DegardinBruno** [comment]
Hey @G0LDF0X!

Training kinetic-gan creates the following folder structure:

```
|-- runs
|   |--kinetic-gan
|   |   |-- exp1                
|   |   |   |-- actions         
|   |   |   `-- models 
|   |   |-- exp2        
|   |   |   |-- actions         
|   |   |   `-- models
|   |   `-- ... 
```

You just need to create a `runs` > `kinetic-gan` > `exp1` folders' structure to save the generated actions. And the generated samples will be saved in the `actions` folder.

I will close this issue, but feel free to open it if needed.
