### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by blankhaha** [DegardinBruno/Kinetic-GAN#12]
Hi @DegardinBruno,
How can I change the action I want in Blender visualization?

**Comment by DegardinBruno** [comment]
Hey @blankhaha, 

After you check the index sample from your generate `.npy` file, you change line 52 with the desired index.
For example, `skl = 25` will render skeleton index 25 from the generated file.

Each generated sample is repeated every 60 samples (for NTU-RGBD) or 120 (for NTU-120-RGBD).

Tell me if you have any problem.
