### ISSUE TITLE
Question about blender visualization

### ISSUE THREAD

**Issue by LaLaLailalai** [DegardinBruno/Kinetic-GAN#15]
Hi Bruno,

I tried to install blender in this [way](https://github.com/TylerGubala/blenderpy), but when I run blender.py, it comes out 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/16380906/183467806-aaef564d-581a-4c9b-b5f9-987d286502d0.png">

And I checked the objects, there were only three: 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/16380906/183467926-e8bbabb2-74d4-474b-8092-a9ca3e0c32a8.png">

Do you know how to fix it?

Thanks a lot.

**Comment by DegardinBruno** [comment]
Hey @LaLaLailalai ,

You need to import this [.blend](https://github.com/DegardinBruno/Kinetic-GAN/blob/main/visualization/file-initial.blend) file from the [visualization](https://github.com/DegardinBruno/Kinetic-GAN/tree/main/visualization) folder to your blender.

Feel free to reopen this issue!

**Comment by LaLaLailalai** [comment]
Hi @DegardinBruno ,

Sorry I didn't understand you. Do you mean physically import the .blend file to the blender using the blender software interface？ But I can only access the server remotely by commands, how can I do it under this situation?

BTW, can you tell me how do you install it and the version of the blender you use?

**Comment by DegardinBruno** [comment]
Please check the [README.md](https://github.com/DegardinBruno/Kinetic-GAN#blender-visualization) section (blender visualization). The blender interface let you import .blend files, don't need to be physically.

**Comment by LaLaLailalai** [comment]
But I can't access the blender interface now. Is it the only way to import it?

**Comment by LaLaLailalai** [comment]
Is it ok if I install blender locally (on my own laptop) and then run the blender.py through pycharm?

**Comment by DegardinBruno** [comment]
> But I can't access the blender interface now. Is it the only way to import it?

Probably not, but it could be way easier if you can access blender interface.
For this case, blender do not use too much gpu process, a laptop should work.

> Is it ok if I install blender locally (on my own laptop) and then run the blender.py through pycharm?

Use the python interpreter from blender, you can check there that you can access all objects easily.

**Comment by LaLaLailalai** [comment]
Hi @DegardinBruno ,

Thanks for your advice and I can run the script in Blender now at least.

But the figures that come out are all black (and it's the samples generated from the pre-trained model that you provided), probably the Armature doesn't in the right position.  I tried to follow your introduction in Readme, but I'm not sure if I understand it correctly.

So do I need to do anything else like set the position of Armature in the blender by using the blender.py? Do I need to add additional code? 

> Armature needs to be at that specific start position (ctrl-z to return),

Do you mean I should do it on the blender interface? I saw the Armature's hip joint is on the original point, is it the start position that you mean?

>  and configure rotation on X-axis for better visualization.
I thought `data = np.array(rotation(data, -110, 0,0))` in blender.py is for rotation on X-axis, and I don't need to do it by myself.
