### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by IDoMathEveryDay** [DegardinBruno/Kinetic-GAN#16]
The download links for datasets are no longer accessable.

**Comment by DegardinBruno** [comment]
@IDoMathEveryDay  We are sorry. Our servers suffered an attack recently. We are recovering everything. I'll let you know as soon as the links are accessible!

**Comment by IDoMathEveryDay** [comment]
Thanks for responding. All the best.

**Comment by DegardinBruno** [comment]
@IDoMathEveryDay server is live again. Tell me if you have any further problem!
