### ISSUE TITLE
Regarding the metric for the 2-coordinate dataset as Human3.6

### ISSUE THREAD

**Issue by StevRamos** [DegardinBruno/Kinetic-GAN#5]
Hi @DegardinBruno 

As you mention, the MMD is not a stable metric. how about adding zero values to the third dimension to get the FID? Have you tried that or do you have in mind what other metric should be used for this 2-coordinate dataset? Thanks.

Stev

**Comment by DegardinBruno** [comment]
Hey @StevRamos 

Nice suggestion, and yes we tried also!
However, the correlation will always be less than 3d coordinate, and we did not have the samples that previous works used to estimate the distribution quality, so we kept with MMD. 
You can easily try it and check by yourself if the FID with zero padding works with your data.

If you need to compare it also with Kinetic-GAN models, and need some help, just let me know!

**Comment by DegardinBruno** [comment]
I'll close this issue, feel free to reopen if needed.
