### ISSUE TITLE
2D Pose Generation 

### ISSUE THREAD

**Issue by sard0r** [DegardinBruno/Kinetic-GAN#6]
Thanks for the great work @DegardinBruno. 

Is there a way to generate 2d pose sequence actions? Does it work as good as 3d ones?
ps: Training on 2d features released from Openpose or other pose estimation networks.

I have been coding WGAN for 2d pose using FCN network. After seeing your work I was amazed.

Thank you!

Hope to get an answer.

**Comment by DegardinBruno** [comment]
Hello @sard0r, thanks for your interest in Kinetic-GAN!

Alright, you need two things:
- First, change the parameter dataset to "h36m" and change these parameters according to what you need and also check the configurations of [Human3.6M models](https://github.com/DegardinBruno/Kinetic-GAN#human36m-10-action-classes):
https://github.com/DegardinBruno/Kinetic-GAN/blob/main/kinetic-gan.py#L32-L35

- Second, check your skeleton structure and change [graph_h36m](https://github.com/DegardinBruno/Kinetic-GAN/blob/main/models/init_gan/graph_h36m.py) file. Change the `neighbor_base` with the connections of your skeleton structure (upsampling and downsampling levels and adjacency matrices will be generated automatically).

Additionally, you can use the following code before the asserts (similar to the [graph_ntu.py](https://github.com/DegardinBruno/Kinetic-GAN/blob/main/models/init_gan/graph_ntu.py)) to visualise your skeleton levels:
```
for i, G in enumerate(self.Gs):  # Uncomment this to visualize graphs
      plt.clf()  # Uncomment this to visualize graphs
      nx.draw(G, with_labels = True)
      plt.savefig('G_' + str(i) + '.pdf')
```

For any additional information, feel free to ask.

**Comment by sard0r** [comment]
Oh thank you very much for the response @DegardinBruno!

I apologize to ask a such question but as I see one of the key words of the Kinetic-GAN GitHub page is Synthetic Data. Can the generated output be used for training pose based action recognition?

Thank you very much! Good Work @DegardinBruno:)

**Comment by DegardinBruno** [comment]
Hey @sard0r,

> Can the generated output be used for training pose based action recognition?

Absolutely, and actually, we are releasing a super dataset in the upcoming months for skeleton-based action recognition.

**Comment by sard0r** [comment]
@DegardinBruno Thank you for your response. I have a question about data preprocessing step. So, now if we extract keypoints using Openpose(tf-openpose) it will give normalized key joints. And looking at the h36m data I think that is not normalized and I was concerned that if we use normalized keypoints would it work or not. 

Thank you very much for your response!

**Comment by DegardinBruno** [comment]
Hey @sard0r, what are the ranges of normalized values? 0 to 1 or -1 to 1 or other values?
There will be no problem at all to normalize again to -1 to 1 for Kinetic-GAN, the representations will be the same just in a different range.
You can check our [feeder file](https://github.com/DegardinBruno/Kinetic-GAN/blob/main/feeder/feeder.py) (line 77).

**Comment by sard0r** [comment]
@DegardinBruno I am very thankful for your response! tf pose gives normalized features in the range of 0 to 1.  I read most of your code and paper so it was great pleasure. Now, I think I should figure out how to use the neighboring link.  I am trying to understand what those numbers represent in keypoints( for ex, Neck, Head, leg). Anyways, great pleasure to get a reply from an expert engineer like you @DegardinBruno. 
![image](https://user-images.githubusercontent.com/61651742/168454196-3c6ec468-512e-4d1e-88ff-c123e56af319.png)

**Comment by DegardinBruno** [comment]
Hello @sard0r, thank you very much for your interest!

These numbers are related to all "bones" (connections) between joints. Each number refers to the indices in the data/tensor/list. **The tuples order is not important**!
I suggest you plot just one skeleton from your data and figure out your order of keypoints. Near each joint, plot its indice. You can use our [scripts](https://github.com/DegardinBruno/Kinetic-GAN/blob/main/visualization/action_h36m.py) (for example, action_h36m.py or any other).
