### ISSUE TITLE
Stochastic Variation

### ISSUE THREAD

**Issue by sard0r** [DegardinBruno/Kinetic-GAN#8]
Good job sir. 

I have a question in terms of generating sequneces of poses for action recognition. 

Have you tested adding generated data with the real data for action recognition? And if possible does it help.

My second question is about stochastic variation. Does stochastic variation mean if you give noise to the network it will generate different actions? 

And how can we generate stochastic actions using Kinetic GAN. I could not found the way to do it. 

Thank you

**Comment by DegardinBruno** [comment]
Hello @sard0r,

> Have you tested adding generated data with the real data for action recognition? And if possible does it help.

Yes, we have, and yes it helps! Good question.

> My second question is about stochastic variation. Does stochastic variation mean if you give noise to the network it will generate different actions?

Exactly! You can check on the generator file (Noise injection).

> And how can we generate stochastic actions using Kinetic GAN. I could not found the way to do it.

I will soon upload it, but basically, when you use the generate.py file, we are also saving the latent point that originates that specific action, so if you use that point multiple times, you will have slightly different actions. Did I make myself clear?
