### ISSUE TITLE
About setting during training

### ISSUE THREAD

**Issue by Amazingren** [DegardinBruno/Kinetic-GAN#9]
Hey @ojoaobrito,

Thanks for your impressive work, it's really interesting. About the training of the proposed model, I have two questions:
1) can the model be trained by multi-GPUs?
2) does the batch_size affect the performance? ( for example, is that fine for me to double the batch size on my machine?)

Best and meant thanks,

**Comment by DegardinBruno** [comment]
Hello @Amazingren,

> 1. can the model be trained by multi-GPUs?

Yes, it can, despite not being adapted for it yet! The training is quite fast with single-GPU since it is the same as working with 64x25 "images".

> 2. does the batch_size affect the performance? ( for example, is that fine for me to double the batch size on my machine?)

It can slightly change a bit, but not much! As long as the batch_size is a base 2 number.

Any further questions, feel free to ask.

**Comment by Amazingren** [comment]
> Hello @Amazingren,
> 
> > 1. can the model be trained by multi-GPUs?
> 
> Yes, it can, despite not being adapted for it yet! The training is quite fast with single-GPU since it is the same as working with 64x25 "images".
> 
> > 2. does the batch_size affect the performance? ( for example, is that fine for me to double the batch size on my machine?)
> 
> It can slightly change a bit, but not much! As long as the batch_size is a base 2 number.
> 
> Any further questions, feel free to ask.

Thanks very much for your time and quick reply. Helps a lot~
